"""
Django settings for huella_hurbana project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
from datetime import timedelta
from decouple import config, Csv 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']

# ============================================
# CONFIGURACIÓN DE CLOUDINARY
# ============================================
cloudinary.config( 
    cloud_name=config('CLOUDINARY_CLOUD_NAME'),
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET'),
    secure=True
)

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
MEDIA_URL = "/media/"

# ============================================
# CONFIGURACIÓN DE CACHE (REQUERIDO PARA RATELIMIT)
# ============================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    }
}

# ============================================
# CONFIGURACIÓN DE LOGIN
# ============================================
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ============================================
# APLICACIONES INSTALADAS
# ============================================
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    
    # Apps de terceros
    'cloudinary',
    'cloudinary_storage',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'axes',  # Protección contra fuerza bruta
        'csp',            # Content Security Policy

    # Tu app
    'server',
        'rest_framework',  # ← Agregar esto
            'corsheaders',  # ← Nuevo



]


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}


# ============================================
# MIDDLEWARE
# ============================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← Debe ir AL PRINCIPIO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'csp.middleware.CSPMiddleware',                     # Content Security Policy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware',  # ← DEBE SER EL ÚLTIMO
]

# Permitir todas las conexiones (para desarrollo)
CORS_ALLOW_ALL_ORIGINS = True

# O ser más específico:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "https://huella-urbana.onrender.com",
]

# ============================================
# BACKENDS DE AUTENTICACIÓN (UNIFICADOS)
# ============================================
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',      # Protección contra fuerza bruta
    'django.contrib.auth.backends.ModelBackend', # Backend por defecto de Django
    'allauth.account.auth_backends.AuthenticationBackend',  # Backend de allauth
]

# ============================================
# CONFIGURACIÓN DE DJANGO-AXES
# ============================================
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # Número de intentos fallidos permitidos
AXES_COOLOFF_TIME = 1  # Horas de bloqueo
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]  # Bloquear por IP y usuario
AXES_RESET_ON_SUCCESS = True  # Reiniciar contador al iniciar sesión correctamente
AXES_ENABLE_ACCESS_FAILURE_LOG = True  # Registrar intentos fallidos

# ============================================
# CONFIGURACIÓN DE DJANGO-ALLAUTH
# ============================================
SITE_ID = 1

# Configuraciones de allauth (versión 0.63+)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGOUT_ON_GET = True  # Permitir logout por GET

ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/300s',  # 5 intentos en 300 segundos (5 minutos)
}

# Protección contra clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protección contra MIME sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Protección XSS en navegadores antiguos
SECURE_BROWSER_XSS_FILTER = True


# ============================================
# CONTENT SECURITY POLICY (CSP) - NUEVO FORMATO
# ============================================
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",
            'https://cdn.jsdelivr.net',
            'https://unpkg.com',
            'https://cdnjs.cloudflare.com',
            'https://code.jquery.com',
            'https://stackpath.bootstrapcdn.com',
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",
            'https://cdn.jsdelivr.net',
            'https://unpkg.com',
            'https://cdnjs.cloudflare.com',
            'https://fonts.googleapis.com',
            'https://stackpath.bootstrapcdn.com',
        ),
        'font-src': (
            "'self'",
            'https://cdnjs.cloudflare.com',
            'https://fonts.gstatic.com',
            'data:',
        ),
        'img-src': (
            "'self'",
            'data:',
            'https://res.cloudinary.com',
            'https://*.basemaps.cartocdn.com',
            'https://raw.githubusercontent.com',
            'blob:',
        ),
        'connect-src': (
            "'self'",
            'https://nominatim.openstreetmap.org',
        ),
        'frame-src': ("'self'",),
        'media-src': ("'self'", 'https://res.cloudinary.com'),
    }
}

# ============================================
# CONFIGURACIÓN DE URLs
# ============================================
ROOT_URLCONF = 'huella_hurbana.urls'


# Política de Referrer
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# ============================================
# CONFIGURACIÓN DE TEMPLATES
# ============================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huella_hurbana.wsgi.application'

# ============================================
# BASE DE DATOS
# ============================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# INTERNACIONALIZACIÓN
# ============================================
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# ============================================
# ARCHIVOS ESTÁTICOS
# ============================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ============================================
# CONFIGURACIÓN POR DEFECTO PARA PK
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ============================================
# LOGGING DE SEGURIDAD
# ============================================
# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'security': {
            'format': '[SECURITY] {asctime} - {levelname} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file_security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 1024 * 1024 * 10,                 # 10MB
            'backupCount': 5,
            'formatter': 'security',
        },
        'file_axes': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'axes.log',
            'maxBytes': 1024 * 1024 * 10,                 # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file_security', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['file_axes', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_security'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# ============================================
# CONFIGURACIÓN DE JAZZMIN (Opcional)
# ============================================
JAZZMIN_SETTINGS = {
    "site_title": "Huella Urbana Admin",
    "site_header": "Huella Urbana",
    "site_brand": "🐾 Huella Urbana",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "Huella Urbana",
    "search_model": ["server.NuevoReporte", "auth.User"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "server.NuevoReporte": "fas fa-file-alt",
        "server.Foto": "fas fa-image",
        "server.PerfilUsuario": "fas fa-id-card",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-purple",
    "accent": "accent-purple",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-purple",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}