# Generated by Django 6.0.4 on 2026-04-21 00:32

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha', models.DateField(verbose_name='Fecha del incidente')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora aproximada')),
                ('tipo_animal', models.CharField(choices=[('perro', 'Perro doméstico'), ('gato', 'Gato'), ('otro', 'Otro animal')], max_length=20, verbose_name='Tipo de animal víctima')),
                ('cantidad_perros', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Cantidad de perros agresores')),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave')], max_length=20, verbose_name='Gravedad del ataque')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('sector', models.CharField(blank=True, choices=[('centro', 'Centro'), ('las_animas', 'Las Ánimas'), ('collico', 'Collico'), ('parque_saval', 'Parque Saval'), ('isla_teja', 'Isla Teja'), ('los_pelues', 'Los Pelúes'), ('angachilla', 'Angachilla'), ('niebla', 'Niebla'), ('otro', 'Otro')], max_length=50, null=True, verbose_name='Sector')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitud')),
                ('nombre_reportante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del reportante')),
                ('email_reportante', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del reportante')),
                ('telefono_reportante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('anonimo', models.BooleanField(default=False, verbose_name='¿Reporte anónimo?')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_moderacion', models.DateTimeField(blank=True, null=True)),
                ('comentario_moderacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moderador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_moderados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ModeracionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('verificado', 'Verificado'), ('rechazado', 'Rechazado'), ('comentario', 'Comentario interno')], max_length=50)),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo o Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('moderador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='server.nuevoreporte')),
            ],
            options={
                'verbose_name': 'Registro de moderación',
                'verbose_name_plural': 'Registros de moderación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('es_censurada', models.BooleanField(default=False, verbose_name='¿Censurada?')),
                ('contiene_contenido_grafico', models.BooleanField(default=False, verbose_name='¿Contiene contenido gráfico?')),
                ('estado_moderacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado de moderación')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='server.nuevoreporte', verbose_name='Reporte asociado')),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
                'ordering': ['orden', '-subida_en'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario Registrado'), ('moderador', 'Moderador'), ('admin', 'Administrador')], default='usuario', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
