# Generated by Django 6.0.4 on 2026-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoreporte',
            name='sector',
        ),
        migrations.AddField(
            model_name='nuevoreporte',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='nuevoreporte',
            name='pais',
            field=models.CharField(blank=True, default='Chile', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='nuevoreporte',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
    ]
