# Generated by Django 6.0.4 on 2026-04-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_nuevoreporte_sector_nuevoreporte_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='fecha_moderacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de moderación'),
        ),
        migrations.AddField(
            model_name='foto',
            name='moderada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_moderadas', to=settings.AUTH_USER_MODEL, verbose_name='Moderada por'),
        ),
        migrations.AddField(
            model_name='foto',
            name='motivo_censura',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo de censura/ocultamiento'),
        ),
        migrations.AddField(
            model_name='foto',
            name='visibilidad',
            field=models.CharField(choices=[('visible', 'Visible al público'), ('censurada', 'Censurada (contenido sensible)'), ('oculta', 'Oculta completamente'), ('pendiente', 'Pendiente de revisión')], default='visible', max_length=20, verbose_name='Visibilidad pública'),
        ),
        migrations.AddField(
            model_name='moderacionlog',
            name='detalles_extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalles adicionales'),
        ),
        migrations.AddField(
            model_name='moderacionlog',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='server.foto', verbose_name='Foto relacionada'),
        ),
        migrations.AddField(
            model_name='nuevoreporte',
            name='contiene_contenido_sensible',
            field=models.BooleanField(default=False, help_text='Marcar si el reporte contiene imágenes de sangre, heridas o violencia', verbose_name='¿Contiene contenido sensible?'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='contiene_contenido_grafico',
            field=models.BooleanField(default=False, verbose_name='¿Contiene contenido gráfico/sensible?'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='es_censurada',
            field=models.BooleanField(default=False, help_text='Campo legacy - Usar visibilidad en su lugar', verbose_name='¿Censurada?'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='estado_moderacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada - Visible públicamente'), ('rechazada', 'Rechazada - No visible')], default='pendiente', max_length=20, verbose_name='Estado de moderación'),
        ),
        migrations.AlterField(
            model_name='moderacionlog',
            name='accion',
            field=models.CharField(choices=[('verificado', 'Verificado'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado permanentemente'), ('comentario', 'Comentario interno'), ('foto_censurada', 'Foto censurada'), ('foto_aprobada', 'Foto aprobada'), ('foto_oculta', 'Foto oculta')], max_length=50, verbose_name='Acción realizada'),
        ),
        migrations.AlterField(
            model_name='moderacionlog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la acción'),
        ),
        migrations.AlterField(
            model_name='moderacionlog',
            name='moderador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Moderador'),
        ),
        migrations.AlterField(
            model_name='moderacionlog',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='server.nuevoreporte'),
        ),
    ]
