# Generated by Django 6.0.4 on 2026-04-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_foto_fecha_moderacion_foto_moderada_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('moderador', 'Moderador'), ('admin', 'Administrador')], default='moderador', max_length=20),
        ),
    ]
