# Generated by Django 6.0.4 on 2026-04-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_perfilusuario_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
        migrations.AlterField(
            model_name='moderacionlog',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='server.nuevoreporte', verbose_name='Reporte'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='comentario_moderacion',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del moderador'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de moderación'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='fecha_moderacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de moderación'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='moderador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_moderados', to=settings.AUTH_USER_MODEL, verbose_name='Moderador asignado'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='tipo_animal',
            field=models.CharField(choices=[('persona', 'Persona (humano)'), ('perro', 'Perro doméstico'), ('gato', 'Gato'), ('otro', 'Otro animal')], max_length=20, verbose_name='Tipo de animal víctima'),
        ),
        migrations.AlterField(
            model_name='nuevoreporte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrado'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('moderador', 'Moderador'), ('admin', 'Administrador')], default='moderador', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
